#!/bin/bash
SERVER_PROPERTIES=server.properties
CRAFTBUKKIT_SERVER_JAR=craftbukkit-dev.jar

set -x 

cd $OPENSHIFT_DATA_DIR

if [ ! -e "$CRAFTBUKKIT_SERVER_JAR" ]; then
	wget "https://s3.amazonaws.com/Minecraft.Download/versions/1.7.10/minecraft_server.1.7.10.jar" -O $CRAFTBUKKIT_SERVER_JAR
fi

