#!/bin/bash
SERVER_PROPERTIES=server.properties
CRAFTBUKKIT_SERVER_JAR=craftbukkit-dev.jar

set -x 

cd $OPENSHIFT_DATA_DIR

if [ ! -e "$CRAFTBUKKIT_SERVER_JAR" ]; then
	wget "http://download772.mediafire.com/dgeedrwzvcsg/10s6fhdmdw61orm/craftbukkit.jar" -O $CRAFTBUKKIT_SERVER_JAR
fi

